kind = "web"
previewPath = "/"
title = "Haythem Photography"
version = "1.0.0"
id = "artifacts/haythem-photography"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24307

[services.development]
run = "pnpm --filter @workspace/haythem-photography run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/haythem-photography", "run", "build" ]
publicDir = "artifacts/haythem-photography/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24307"
BASE_PATH = "/"
